// flow-typed signature: 10786ff7a9a2b2c61b2079e9dff54da2
// flow-typed version: <<STUB>>/@mdi/js_v3.0.39/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mdi/js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mdi/js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mdi/js/build' {
  declare module.exports: any;
}

declare module '@mdi/js/commonjs/mdi' {
  declare module.exports: any;
}

declare module '@mdi/js/mdi' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mdi/js/build.js' {
  declare module.exports: $Exports<'@mdi/js/build'>;
}
declare module '@mdi/js/commonjs/mdi.js' {
  declare module.exports: $Exports<'@mdi/js/commonjs/mdi'>;
}
declare module '@mdi/js/mdi.js' {
  declare module.exports: $Exports<'@mdi/js/mdi'>;
}
