// flow-typed signature: 3d38c058fdf7bb9898842b4e4b9c7b53
// flow-typed version: <<STUB>>/@mdi/react_v1.1.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mdi/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mdi/react' {
  declare export default class Icon extends React$Component<{|
    path: string,
    size?: number | string,
    horizontal?: boolean,
    vertical?: boolean,
    rotate?: number,
    color?: string,
    spin?: boolean | number,
  |}> {}
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mdi/react/Icon' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mdi/react/Icon.js' {
  declare module.exports: $Exports<'@mdi/react/Icon'>;
}
