// flow-typed signature: e9bb1379bb4d32b31e86aa601ba054c8
// flow-typed version: <<STUB>>/d3-ease_v^1.0.3/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-ease'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-ease' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-ease/build/d3-ease' {
  declare module.exports: any;
}

declare module 'd3-ease/build/d3-ease.min' {
  declare module.exports: any;
}

declare module 'd3-ease/src/back' {
  declare module.exports: any;
}

declare module 'd3-ease/src/bounce' {
  declare module.exports: any;
}

declare module 'd3-ease/src/circle' {
  declare module.exports: any;
}

declare module 'd3-ease/src/cubic' {
  declare module.exports: any;
}

declare module 'd3-ease/src/elastic' {
  declare module.exports: any;
}

declare module 'd3-ease/src/exp' {
  declare module.exports: any;
}

declare module 'd3-ease/src/linear' {
  declare module.exports: any;
}

declare module 'd3-ease/src/poly' {
  declare module.exports: any;
}

declare module 'd3-ease/src/quad' {
  declare module.exports: any;
}

declare module 'd3-ease/src/sin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-ease/build/d3-ease.js' {
  declare module.exports: $Exports<'d3-ease/build/d3-ease'>;
}
declare module 'd3-ease/build/d3-ease.min.js' {
  declare module.exports: $Exports<'d3-ease/build/d3-ease.min'>;
}
declare module 'd3-ease/index' {
  declare module.exports: $Exports<'d3-ease'>;
}
declare module 'd3-ease/index.js' {
  declare module.exports: $Exports<'d3-ease'>;
}
declare module 'd3-ease/src/back.js' {
  declare module.exports: $Exports<'d3-ease/src/back'>;
}
declare module 'd3-ease/src/bounce.js' {
  declare module.exports: $Exports<'d3-ease/src/bounce'>;
}
declare module 'd3-ease/src/circle.js' {
  declare module.exports: $Exports<'d3-ease/src/circle'>;
}
declare module 'd3-ease/src/cubic.js' {
  declare module.exports: $Exports<'d3-ease/src/cubic'>;
}
declare module 'd3-ease/src/elastic.js' {
  declare module.exports: $Exports<'d3-ease/src/elastic'>;
}
declare module 'd3-ease/src/exp.js' {
  declare module.exports: $Exports<'d3-ease/src/exp'>;
}
declare module 'd3-ease/src/linear.js' {
  declare module.exports: $Exports<'d3-ease/src/linear'>;
}
declare module 'd3-ease/src/poly.js' {
  declare module.exports: $Exports<'d3-ease/src/poly'>;
}
declare module 'd3-ease/src/quad.js' {
  declare module.exports: $Exports<'d3-ease/src/quad'>;
}
declare module 'd3-ease/src/sin.js' {
  declare module.exports: $Exports<'d3-ease/src/sin'>;
}
