// flow-typed signature: 5b4c0aebc27188bcdfbf5bd3646f7c92
// flow-typed version: <<STUB>>/d3-scale-chromatic_v^1.2.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-scale-chromatic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-scale-chromatic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-scale-chromatic/dist/d3-scale-chromatic' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/dist/d3-scale-chromatic.min' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/rollup.config' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/categorical/Accent' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/categorical/category10' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/categorical/Dark2' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/categorical/Paired' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/categorical/Pastel1' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/categorical/Pastel2' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/categorical/Set1' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/categorical/Set2' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/categorical/Set3' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/colors' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/diverging/BrBG' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/diverging/PiYG' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/diverging/PRGn' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/diverging/PuOr' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/diverging/RdBu' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/diverging/RdGy' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/diverging/RdYlBu' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/diverging/RdYlGn' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/diverging/Spectral' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/ramp' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/rampClosed' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/scheme' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-multi/BuGn' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-multi/BuPu' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-multi/cubehelix' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-multi/GnBu' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-multi/OrRd' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-multi/PuBu' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-multi/PuBuGn' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-multi/PuRd' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-multi/rainbow' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-multi/RdPu' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-multi/viridis' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-multi/YlGn' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-multi/YlGnBu' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-multi/YlOrBr' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-multi/YlOrRd' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-single/Blues' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-single/Greens' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-single/Greys' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-single/Oranges' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-single/Purples' {
  declare module.exports: any;
}

declare module 'd3-scale-chromatic/src/sequential-single/Reds' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-scale-chromatic/dist/d3-scale-chromatic.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/dist/d3-scale-chromatic'>;
}
declare module 'd3-scale-chromatic/dist/d3-scale-chromatic.min.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/dist/d3-scale-chromatic.min'>;
}
declare module 'd3-scale-chromatic/index' {
  declare module.exports: $Exports<'d3-scale-chromatic'>;
}
declare module 'd3-scale-chromatic/index.js' {
  declare module.exports: $Exports<'d3-scale-chromatic'>;
}
declare module 'd3-scale-chromatic/rollup.config.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/rollup.config'>;
}
declare module 'd3-scale-chromatic/src/categorical/Accent.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/categorical/Accent'>;
}
declare module 'd3-scale-chromatic/src/categorical/category10.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/categorical/category10'>;
}
declare module 'd3-scale-chromatic/src/categorical/Dark2.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/categorical/Dark2'>;
}
declare module 'd3-scale-chromatic/src/categorical/Paired.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/categorical/Paired'>;
}
declare module 'd3-scale-chromatic/src/categorical/Pastel1.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/categorical/Pastel1'>;
}
declare module 'd3-scale-chromatic/src/categorical/Pastel2.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/categorical/Pastel2'>;
}
declare module 'd3-scale-chromatic/src/categorical/Set1.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/categorical/Set1'>;
}
declare module 'd3-scale-chromatic/src/categorical/Set2.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/categorical/Set2'>;
}
declare module 'd3-scale-chromatic/src/categorical/Set3.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/categorical/Set3'>;
}
declare module 'd3-scale-chromatic/src/colors.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/colors'>;
}
declare module 'd3-scale-chromatic/src/diverging/BrBG.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/diverging/BrBG'>;
}
declare module 'd3-scale-chromatic/src/diverging/PiYG.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/diverging/PiYG'>;
}
declare module 'd3-scale-chromatic/src/diverging/PRGn.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/diverging/PRGn'>;
}
declare module 'd3-scale-chromatic/src/diverging/PuOr.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/diverging/PuOr'>;
}
declare module 'd3-scale-chromatic/src/diverging/RdBu.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/diverging/RdBu'>;
}
declare module 'd3-scale-chromatic/src/diverging/RdGy.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/diverging/RdGy'>;
}
declare module 'd3-scale-chromatic/src/diverging/RdYlBu.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/diverging/RdYlBu'>;
}
declare module 'd3-scale-chromatic/src/diverging/RdYlGn.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/diverging/RdYlGn'>;
}
declare module 'd3-scale-chromatic/src/diverging/Spectral.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/diverging/Spectral'>;
}
declare module 'd3-scale-chromatic/src/ramp.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/ramp'>;
}
declare module 'd3-scale-chromatic/src/rampClosed.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/rampClosed'>;
}
declare module 'd3-scale-chromatic/src/scheme.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/scheme'>;
}
declare module 'd3-scale-chromatic/src/sequential-multi/BuGn.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-multi/BuGn'>;
}
declare module 'd3-scale-chromatic/src/sequential-multi/BuPu.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-multi/BuPu'>;
}
declare module 'd3-scale-chromatic/src/sequential-multi/cubehelix.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-multi/cubehelix'>;
}
declare module 'd3-scale-chromatic/src/sequential-multi/GnBu.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-multi/GnBu'>;
}
declare module 'd3-scale-chromatic/src/sequential-multi/OrRd.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-multi/OrRd'>;
}
declare module 'd3-scale-chromatic/src/sequential-multi/PuBu.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-multi/PuBu'>;
}
declare module 'd3-scale-chromatic/src/sequential-multi/PuBuGn.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-multi/PuBuGn'>;
}
declare module 'd3-scale-chromatic/src/sequential-multi/PuRd.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-multi/PuRd'>;
}
declare module 'd3-scale-chromatic/src/sequential-multi/rainbow.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-multi/rainbow'>;
}
declare module 'd3-scale-chromatic/src/sequential-multi/RdPu.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-multi/RdPu'>;
}
declare module 'd3-scale-chromatic/src/sequential-multi/viridis.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-multi/viridis'>;
}
declare module 'd3-scale-chromatic/src/sequential-multi/YlGn.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-multi/YlGn'>;
}
declare module 'd3-scale-chromatic/src/sequential-multi/YlGnBu.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-multi/YlGnBu'>;
}
declare module 'd3-scale-chromatic/src/sequential-multi/YlOrBr.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-multi/YlOrBr'>;
}
declare module 'd3-scale-chromatic/src/sequential-multi/YlOrRd.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-multi/YlOrRd'>;
}
declare module 'd3-scale-chromatic/src/sequential-single/Blues.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-single/Blues'>;
}
declare module 'd3-scale-chromatic/src/sequential-single/Greens.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-single/Greens'>;
}
declare module 'd3-scale-chromatic/src/sequential-single/Greys.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-single/Greys'>;
}
declare module 'd3-scale-chromatic/src/sequential-single/Oranges.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-single/Oranges'>;
}
declare module 'd3-scale-chromatic/src/sequential-single/Purples.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-single/Purples'>;
}
declare module 'd3-scale-chromatic/src/sequential-single/Reds.js' {
  declare module.exports: $Exports<'d3-scale-chromatic/src/sequential-single/Reds'>;
}
