// flow-typed signature: 6aa51813b37b3e855a5df1f24589d0ee
// flow-typed version: <<STUB>>/mdi_v^2.2.43/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mdi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mdi' {
  declare module.exports: any;
}
