// flow-typed signature: 208fcc05745739717e0bc0563755a31c
// flow-typed version: <<STUB>>/react-event-listener_v^0.5.3/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-event-listener'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-event-listener' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-event-listener/lib/index' {
  declare module.exports: any;
}

declare module 'react-event-listener/lib/supports' {
  declare module.exports: any;
}

declare module 'react-event-listener/src/index' {
  declare module.exports: any;
}

declare module 'react-event-listener/src/supports' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-event-listener/lib/index.js' {
  declare module.exports: $Exports<'react-event-listener/lib/index'>;
}
declare module 'react-event-listener/lib/supports.js' {
  declare module.exports: $Exports<'react-event-listener/lib/supports'>;
}
declare module 'react-event-listener/src/index.js' {
  declare module.exports: $Exports<'react-event-listener/src/index'>;
}
declare module 'react-event-listener/src/supports.js' {
  declare module.exports: $Exports<'react-event-listener/src/supports'>;
}
