// flow-typed signature: 7c1c1b79d40759332d6aee8289b112b4
// flow-typed version: <<STUB>>/toxiclibsjs_v^0.3.3/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'toxiclibsjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'toxiclibsjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'toxiclibsjs/color' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/accessCriteria' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/accessors' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/AlphaAccessor' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/CMYKAccessor' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/CMYKDistanceProxy' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/ColorGradient' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/ColorList' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/ColorRange' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/ColorTheme' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/createListUsingStrategy' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/distanceProxies' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/HistEntry' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/Histogram' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/HSVAccessor' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/HSVDistanceProxy' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/Hue' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/LuminanceAccessor' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/namedColor' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/ProximityComparator' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/RGBAccessor' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/RGBDistanceProxy' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/TColor' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/theory' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/theory/AnalagousStrategy' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/theory/colorTheoryRegistry' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/theory/ComplementaryStrategy' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/theory/CompoundTheoryStrategy' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/theory/LeftSplitComplementaryStrategy' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/theory/MonochromeTheoryStrategy' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/theory/RightSplitComplementaryStrategy' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/theory/SingleComplementStrategy' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/theory/SplitComplementaryStrategy' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/theory/strategies' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/theory/TetradTheoryStrategy' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/theory/TriadTheoryStrategy' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/color/ToneMap' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/AABB' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/AxisAlignedCylinder' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/BernsteinPolynomial' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Circle' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/CircleIntersector' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Cone' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/ConvexPolygonClipper' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Ellipse' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/IsectData2D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/IsectData3D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Line2D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Line3D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/LineStrip3D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Matrix4x4' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/BezierPatch' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/BoxSelector' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/DefaultSelector' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/Face' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/meshCommon' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/OBJWriter' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/PlaneSelector' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/SphereFunction' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/SphericalHarmonics' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/subdiv' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/subdiv/DisplacementSubdivision' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/subdiv/DualDisplacementSubdivision' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/subdiv/DualSubdivision' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/subdiv/EdgeLengthComparator' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/subdiv/FaceCountComparator' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/subdiv/MidpointDisplacementSubdivision' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/subdiv/MidpointSubdivision' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/subdiv/NormalDisplacementSubdivision' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/subdiv/SubdivisionStrategy' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/subdiv/TriSubdivision' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/SuperEllipsoid' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/SurfaceMeshBuilder' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/Terrain' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/TriangleMesh' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/Vertex' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/VertexSelector' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/WEFace' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/WETriangleMesh' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/WEVertex' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/mesh/WingedEdge' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Plane' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Polygon2D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Quaternion' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Ray2D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Ray3D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Ray3DIntersector' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Rect' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Sphere' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Spline2D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Spline3D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/SutherlandHodgemanClipper' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Triangle2D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Triangle3D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/TriangleIntersector' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Vec2D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/Vec3D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/vectors' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/XAxisCylinder' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/YAxisCylinder' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/geom/ZAxisCylinder' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/internals' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/internals/bind' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/internals/each' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/internals/extend' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/internals/filter' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/internals/has' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/internals/is' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/internals/Iterator' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/internals/keys' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/internals/LinkedMap' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/internals/mixin' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/internals/numberComparator' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/internals/removeItemFrom' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/internals/values' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/BezierInterpolation' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/CircularInterpolation' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/conversion/index' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/conversion/UnitTranslator' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/CosineInterpolation' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/DecimatedInterpolation' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/ExponentialInterpolation' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/Interpolation2D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/LinearInterpolation' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/mathUtils' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/noise' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/noise/PerlinNoise' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/noise/simplexNoise' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/ScaleMap' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/SigmoidInterpolation' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/SinCosLUT' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/ThresholdInterpolation' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/waves' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/waves/AbstractWave' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/waves/AMFMSineWave' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/waves/ConstantWave' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/waves/FMHarmonicSquareWave' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/waves/FMSawtoothWave' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/waves/FMSineWave' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/waves/FMSquareWave' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/waves/FMTriangleWave' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/waves/SineWave' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/waves/WaveState' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/math/ZoomLensInterpolation' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/behaviors' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/behaviors/AttractionBehavior' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/behaviors/ConstantForceBehavior' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/behaviors/GravityBehavior' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/constraints' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/constraints/AngularConstraint' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/constraints/AxisConstraint' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/constraints/CircularConstraint' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/constraints/MaxConstraint' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/constraints/MinConstraint' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/constraints/RectConstraint' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/ParticlePath2D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/ParticleString2D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/PullBackString2D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/VerletConstrainedSpring2D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/VerletMinDistanceSpring2D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/VerletParticle2D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/VerletPhysics2D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/physics2d/VerletSpring2D' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/processing' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/processing/ToxiclibsSupport' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/THREE' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/THREE/ToxiclibsSupport' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/util' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/util/datatypes' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/util/datatypes/ArraySet' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/util/datatypes/FloatRange' {
  declare module.exports: any;
}

declare module 'toxiclibsjs/util/datatypes/UndirectedGraph' {
  declare module.exports: any;
}

// Filename aliases
declare module 'toxiclibsjs/color.js' {
  declare module.exports: $Exports<'toxiclibsjs/color'>;
}
declare module 'toxiclibsjs/color/accessCriteria.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/accessCriteria'>;
}
declare module 'toxiclibsjs/color/accessors.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/accessors'>;
}
declare module 'toxiclibsjs/color/AlphaAccessor.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/AlphaAccessor'>;
}
declare module 'toxiclibsjs/color/CMYKAccessor.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/CMYKAccessor'>;
}
declare module 'toxiclibsjs/color/CMYKDistanceProxy.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/CMYKDistanceProxy'>;
}
declare module 'toxiclibsjs/color/ColorGradient.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/ColorGradient'>;
}
declare module 'toxiclibsjs/color/ColorList.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/ColorList'>;
}
declare module 'toxiclibsjs/color/ColorRange.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/ColorRange'>;
}
declare module 'toxiclibsjs/color/ColorTheme.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/ColorTheme'>;
}
declare module 'toxiclibsjs/color/createListUsingStrategy.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/createListUsingStrategy'>;
}
declare module 'toxiclibsjs/color/distanceProxies.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/distanceProxies'>;
}
declare module 'toxiclibsjs/color/HistEntry.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/HistEntry'>;
}
declare module 'toxiclibsjs/color/Histogram.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/Histogram'>;
}
declare module 'toxiclibsjs/color/HSVAccessor.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/HSVAccessor'>;
}
declare module 'toxiclibsjs/color/HSVDistanceProxy.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/HSVDistanceProxy'>;
}
declare module 'toxiclibsjs/color/Hue.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/Hue'>;
}
declare module 'toxiclibsjs/color/LuminanceAccessor.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/LuminanceAccessor'>;
}
declare module 'toxiclibsjs/color/namedColor.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/namedColor'>;
}
declare module 'toxiclibsjs/color/ProximityComparator.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/ProximityComparator'>;
}
declare module 'toxiclibsjs/color/RGBAccessor.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/RGBAccessor'>;
}
declare module 'toxiclibsjs/color/RGBDistanceProxy.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/RGBDistanceProxy'>;
}
declare module 'toxiclibsjs/color/TColor.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/TColor'>;
}
declare module 'toxiclibsjs/color/theory.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/theory'>;
}
declare module 'toxiclibsjs/color/theory/AnalagousStrategy.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/theory/AnalagousStrategy'>;
}
declare module 'toxiclibsjs/color/theory/colorTheoryRegistry.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/theory/colorTheoryRegistry'>;
}
declare module 'toxiclibsjs/color/theory/ComplementaryStrategy.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/theory/ComplementaryStrategy'>;
}
declare module 'toxiclibsjs/color/theory/CompoundTheoryStrategy.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/theory/CompoundTheoryStrategy'>;
}
declare module 'toxiclibsjs/color/theory/LeftSplitComplementaryStrategy.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/theory/LeftSplitComplementaryStrategy'>;
}
declare module 'toxiclibsjs/color/theory/MonochromeTheoryStrategy.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/theory/MonochromeTheoryStrategy'>;
}
declare module 'toxiclibsjs/color/theory/RightSplitComplementaryStrategy.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/theory/RightSplitComplementaryStrategy'>;
}
declare module 'toxiclibsjs/color/theory/SingleComplementStrategy.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/theory/SingleComplementStrategy'>;
}
declare module 'toxiclibsjs/color/theory/SplitComplementaryStrategy.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/theory/SplitComplementaryStrategy'>;
}
declare module 'toxiclibsjs/color/theory/strategies.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/theory/strategies'>;
}
declare module 'toxiclibsjs/color/theory/TetradTheoryStrategy.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/theory/TetradTheoryStrategy'>;
}
declare module 'toxiclibsjs/color/theory/TriadTheoryStrategy.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/theory/TriadTheoryStrategy'>;
}
declare module 'toxiclibsjs/color/ToneMap.js' {
  declare module.exports: $Exports<'toxiclibsjs/color/ToneMap'>;
}
declare module 'toxiclibsjs/geom.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom'>;
}
declare module 'toxiclibsjs/geom/AABB.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/AABB'>;
}
declare module 'toxiclibsjs/geom/AxisAlignedCylinder.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/AxisAlignedCylinder'>;
}
declare module 'toxiclibsjs/geom/BernsteinPolynomial.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/BernsteinPolynomial'>;
}
declare module 'toxiclibsjs/geom/Circle.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Circle'>;
}
declare module 'toxiclibsjs/geom/CircleIntersector.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/CircleIntersector'>;
}
declare module 'toxiclibsjs/geom/Cone.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Cone'>;
}
declare module 'toxiclibsjs/geom/ConvexPolygonClipper.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/ConvexPolygonClipper'>;
}
declare module 'toxiclibsjs/geom/Ellipse.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Ellipse'>;
}
declare module 'toxiclibsjs/geom/IsectData2D.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/IsectData2D'>;
}
declare module 'toxiclibsjs/geom/IsectData3D.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/IsectData3D'>;
}
declare module 'toxiclibsjs/geom/Line2D.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Line2D'>;
}
declare module 'toxiclibsjs/geom/Line3D.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Line3D'>;
}
declare module 'toxiclibsjs/geom/LineStrip3D.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/LineStrip3D'>;
}
declare module 'toxiclibsjs/geom/Matrix4x4.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Matrix4x4'>;
}
declare module 'toxiclibsjs/geom/mesh.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh'>;
}
declare module 'toxiclibsjs/geom/mesh/BezierPatch.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/BezierPatch'>;
}
declare module 'toxiclibsjs/geom/mesh/BoxSelector.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/BoxSelector'>;
}
declare module 'toxiclibsjs/geom/mesh/DefaultSelector.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/DefaultSelector'>;
}
declare module 'toxiclibsjs/geom/mesh/Face.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/Face'>;
}
declare module 'toxiclibsjs/geom/mesh/meshCommon.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/meshCommon'>;
}
declare module 'toxiclibsjs/geom/mesh/OBJWriter.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/OBJWriter'>;
}
declare module 'toxiclibsjs/geom/mesh/PlaneSelector.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/PlaneSelector'>;
}
declare module 'toxiclibsjs/geom/mesh/SphereFunction.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/SphereFunction'>;
}
declare module 'toxiclibsjs/geom/mesh/SphericalHarmonics.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/SphericalHarmonics'>;
}
declare module 'toxiclibsjs/geom/mesh/subdiv.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/subdiv'>;
}
declare module 'toxiclibsjs/geom/mesh/subdiv/DisplacementSubdivision.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/subdiv/DisplacementSubdivision'>;
}
declare module 'toxiclibsjs/geom/mesh/subdiv/DualDisplacementSubdivision.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/subdiv/DualDisplacementSubdivision'>;
}
declare module 'toxiclibsjs/geom/mesh/subdiv/DualSubdivision.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/subdiv/DualSubdivision'>;
}
declare module 'toxiclibsjs/geom/mesh/subdiv/EdgeLengthComparator.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/subdiv/EdgeLengthComparator'>;
}
declare module 'toxiclibsjs/geom/mesh/subdiv/FaceCountComparator.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/subdiv/FaceCountComparator'>;
}
declare module 'toxiclibsjs/geom/mesh/subdiv/MidpointDisplacementSubdivision.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/subdiv/MidpointDisplacementSubdivision'>;
}
declare module 'toxiclibsjs/geom/mesh/subdiv/MidpointSubdivision.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/subdiv/MidpointSubdivision'>;
}
declare module 'toxiclibsjs/geom/mesh/subdiv/NormalDisplacementSubdivision.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/subdiv/NormalDisplacementSubdivision'>;
}
declare module 'toxiclibsjs/geom/mesh/subdiv/SubdivisionStrategy.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/subdiv/SubdivisionStrategy'>;
}
declare module 'toxiclibsjs/geom/mesh/subdiv/TriSubdivision.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/subdiv/TriSubdivision'>;
}
declare module 'toxiclibsjs/geom/mesh/SuperEllipsoid.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/SuperEllipsoid'>;
}
declare module 'toxiclibsjs/geom/mesh/SurfaceMeshBuilder.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/SurfaceMeshBuilder'>;
}
declare module 'toxiclibsjs/geom/mesh/Terrain.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/Terrain'>;
}
declare module 'toxiclibsjs/geom/mesh/TriangleMesh.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/TriangleMesh'>;
}
declare module 'toxiclibsjs/geom/mesh/Vertex.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/Vertex'>;
}
declare module 'toxiclibsjs/geom/mesh/VertexSelector.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/VertexSelector'>;
}
declare module 'toxiclibsjs/geom/mesh/WEFace.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/WEFace'>;
}
declare module 'toxiclibsjs/geom/mesh/WETriangleMesh.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/WETriangleMesh'>;
}
declare module 'toxiclibsjs/geom/mesh/WEVertex.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/WEVertex'>;
}
declare module 'toxiclibsjs/geom/mesh/WingedEdge.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/mesh/WingedEdge'>;
}
declare module 'toxiclibsjs/geom/Plane.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Plane'>;
}
declare module 'toxiclibsjs/geom/Polygon2D.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Polygon2D'>;
}
declare module 'toxiclibsjs/geom/Quaternion.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Quaternion'>;
}
declare module 'toxiclibsjs/geom/Ray2D.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Ray2D'>;
}
declare module 'toxiclibsjs/geom/Ray3D.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Ray3D'>;
}
declare module 'toxiclibsjs/geom/Ray3DIntersector.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Ray3DIntersector'>;
}
declare module 'toxiclibsjs/geom/Rect.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Rect'>;
}
declare module 'toxiclibsjs/geom/Sphere.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Sphere'>;
}
declare module 'toxiclibsjs/geom/Spline2D.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Spline2D'>;
}
declare module 'toxiclibsjs/geom/Spline3D.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Spline3D'>;
}
declare module 'toxiclibsjs/geom/SutherlandHodgemanClipper.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/SutherlandHodgemanClipper'>;
}
declare module 'toxiclibsjs/geom/Triangle2D.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Triangle2D'>;
}
declare module 'toxiclibsjs/geom/Triangle3D.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Triangle3D'>;
}
declare module 'toxiclibsjs/geom/TriangleIntersector.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/TriangleIntersector'>;
}
declare module 'toxiclibsjs/geom/Vec2D.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Vec2D'>;
}
declare module 'toxiclibsjs/geom/Vec3D.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/Vec3D'>;
}
declare module 'toxiclibsjs/geom/vectors.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/vectors'>;
}
declare module 'toxiclibsjs/geom/XAxisCylinder.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/XAxisCylinder'>;
}
declare module 'toxiclibsjs/geom/YAxisCylinder.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/YAxisCylinder'>;
}
declare module 'toxiclibsjs/geom/ZAxisCylinder.js' {
  declare module.exports: $Exports<'toxiclibsjs/geom/ZAxisCylinder'>;
}
declare module 'toxiclibsjs/index' {
  declare module.exports: $Exports<'toxiclibsjs'>;
}
declare module 'toxiclibsjs/index.js' {
  declare module.exports: $Exports<'toxiclibsjs'>;
}
declare module 'toxiclibsjs/internals.js' {
  declare module.exports: $Exports<'toxiclibsjs/internals'>;
}
declare module 'toxiclibsjs/internals/bind.js' {
  declare module.exports: $Exports<'toxiclibsjs/internals/bind'>;
}
declare module 'toxiclibsjs/internals/each.js' {
  declare module.exports: $Exports<'toxiclibsjs/internals/each'>;
}
declare module 'toxiclibsjs/internals/extend.js' {
  declare module.exports: $Exports<'toxiclibsjs/internals/extend'>;
}
declare module 'toxiclibsjs/internals/filter.js' {
  declare module.exports: $Exports<'toxiclibsjs/internals/filter'>;
}
declare module 'toxiclibsjs/internals/has.js' {
  declare module.exports: $Exports<'toxiclibsjs/internals/has'>;
}
declare module 'toxiclibsjs/internals/is.js' {
  declare module.exports: $Exports<'toxiclibsjs/internals/is'>;
}
declare module 'toxiclibsjs/internals/Iterator.js' {
  declare module.exports: $Exports<'toxiclibsjs/internals/Iterator'>;
}
declare module 'toxiclibsjs/internals/keys.js' {
  declare module.exports: $Exports<'toxiclibsjs/internals/keys'>;
}
declare module 'toxiclibsjs/internals/LinkedMap.js' {
  declare module.exports: $Exports<'toxiclibsjs/internals/LinkedMap'>;
}
declare module 'toxiclibsjs/internals/mixin.js' {
  declare module.exports: $Exports<'toxiclibsjs/internals/mixin'>;
}
declare module 'toxiclibsjs/internals/numberComparator.js' {
  declare module.exports: $Exports<'toxiclibsjs/internals/numberComparator'>;
}
declare module 'toxiclibsjs/internals/removeItemFrom.js' {
  declare module.exports: $Exports<'toxiclibsjs/internals/removeItemFrom'>;
}
declare module 'toxiclibsjs/internals/values.js' {
  declare module.exports: $Exports<'toxiclibsjs/internals/values'>;
}
declare module 'toxiclibsjs/math.js' {
  declare module.exports: $Exports<'toxiclibsjs/math'>;
}
declare module 'toxiclibsjs/math/BezierInterpolation.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/BezierInterpolation'>;
}
declare module 'toxiclibsjs/math/CircularInterpolation.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/CircularInterpolation'>;
}
declare module 'toxiclibsjs/math/conversion/index.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/conversion/index'>;
}
declare module 'toxiclibsjs/math/conversion/UnitTranslator.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/conversion/UnitTranslator'>;
}
declare module 'toxiclibsjs/math/CosineInterpolation.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/CosineInterpolation'>;
}
declare module 'toxiclibsjs/math/DecimatedInterpolation.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/DecimatedInterpolation'>;
}
declare module 'toxiclibsjs/math/ExponentialInterpolation.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/ExponentialInterpolation'>;
}
declare module 'toxiclibsjs/math/Interpolation2D.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/Interpolation2D'>;
}
declare module 'toxiclibsjs/math/LinearInterpolation.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/LinearInterpolation'>;
}
declare module 'toxiclibsjs/math/mathUtils.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/mathUtils'>;
}
declare module 'toxiclibsjs/math/noise.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/noise'>;
}
declare module 'toxiclibsjs/math/noise/PerlinNoise.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/noise/PerlinNoise'>;
}
declare module 'toxiclibsjs/math/noise/simplexNoise.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/noise/simplexNoise'>;
}
declare module 'toxiclibsjs/math/ScaleMap.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/ScaleMap'>;
}
declare module 'toxiclibsjs/math/SigmoidInterpolation.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/SigmoidInterpolation'>;
}
declare module 'toxiclibsjs/math/SinCosLUT.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/SinCosLUT'>;
}
declare module 'toxiclibsjs/math/ThresholdInterpolation.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/ThresholdInterpolation'>;
}
declare module 'toxiclibsjs/math/waves.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/waves'>;
}
declare module 'toxiclibsjs/math/waves/AbstractWave.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/waves/AbstractWave'>;
}
declare module 'toxiclibsjs/math/waves/AMFMSineWave.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/waves/AMFMSineWave'>;
}
declare module 'toxiclibsjs/math/waves/ConstantWave.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/waves/ConstantWave'>;
}
declare module 'toxiclibsjs/math/waves/FMHarmonicSquareWave.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/waves/FMHarmonicSquareWave'>;
}
declare module 'toxiclibsjs/math/waves/FMSawtoothWave.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/waves/FMSawtoothWave'>;
}
declare module 'toxiclibsjs/math/waves/FMSineWave.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/waves/FMSineWave'>;
}
declare module 'toxiclibsjs/math/waves/FMSquareWave.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/waves/FMSquareWave'>;
}
declare module 'toxiclibsjs/math/waves/FMTriangleWave.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/waves/FMTriangleWave'>;
}
declare module 'toxiclibsjs/math/waves/SineWave.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/waves/SineWave'>;
}
declare module 'toxiclibsjs/math/waves/WaveState.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/waves/WaveState'>;
}
declare module 'toxiclibsjs/math/ZoomLensInterpolation.js' {
  declare module.exports: $Exports<'toxiclibsjs/math/ZoomLensInterpolation'>;
}
declare module 'toxiclibsjs/physics2d.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d'>;
}
declare module 'toxiclibsjs/physics2d/behaviors.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/behaviors'>;
}
declare module 'toxiclibsjs/physics2d/behaviors/AttractionBehavior.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/behaviors/AttractionBehavior'>;
}
declare module 'toxiclibsjs/physics2d/behaviors/ConstantForceBehavior.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/behaviors/ConstantForceBehavior'>;
}
declare module 'toxiclibsjs/physics2d/behaviors/GravityBehavior.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/behaviors/GravityBehavior'>;
}
declare module 'toxiclibsjs/physics2d/constraints.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/constraints'>;
}
declare module 'toxiclibsjs/physics2d/constraints/AngularConstraint.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/constraints/AngularConstraint'>;
}
declare module 'toxiclibsjs/physics2d/constraints/AxisConstraint.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/constraints/AxisConstraint'>;
}
declare module 'toxiclibsjs/physics2d/constraints/CircularConstraint.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/constraints/CircularConstraint'>;
}
declare module 'toxiclibsjs/physics2d/constraints/MaxConstraint.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/constraints/MaxConstraint'>;
}
declare module 'toxiclibsjs/physics2d/constraints/MinConstraint.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/constraints/MinConstraint'>;
}
declare module 'toxiclibsjs/physics2d/constraints/RectConstraint.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/constraints/RectConstraint'>;
}
declare module 'toxiclibsjs/physics2d/ParticlePath2D.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/ParticlePath2D'>;
}
declare module 'toxiclibsjs/physics2d/ParticleString2D.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/ParticleString2D'>;
}
declare module 'toxiclibsjs/physics2d/PullBackString2D.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/PullBackString2D'>;
}
declare module 'toxiclibsjs/physics2d/VerletConstrainedSpring2D.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/VerletConstrainedSpring2D'>;
}
declare module 'toxiclibsjs/physics2d/VerletMinDistanceSpring2D.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/VerletMinDistanceSpring2D'>;
}
declare module 'toxiclibsjs/physics2d/VerletParticle2D.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/VerletParticle2D'>;
}
declare module 'toxiclibsjs/physics2d/VerletPhysics2D.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/VerletPhysics2D'>;
}
declare module 'toxiclibsjs/physics2d/VerletSpring2D.js' {
  declare module.exports: $Exports<'toxiclibsjs/physics2d/VerletSpring2D'>;
}
declare module 'toxiclibsjs/processing.js' {
  declare module.exports: $Exports<'toxiclibsjs/processing'>;
}
declare module 'toxiclibsjs/processing/ToxiclibsSupport.js' {
  declare module.exports: $Exports<'toxiclibsjs/processing/ToxiclibsSupport'>;
}
declare module 'toxiclibsjs/THREE.js' {
  declare module.exports: $Exports<'toxiclibsjs/THREE'>;
}
declare module 'toxiclibsjs/THREE/ToxiclibsSupport.js' {
  declare module.exports: $Exports<'toxiclibsjs/THREE/ToxiclibsSupport'>;
}
declare module 'toxiclibsjs/util.js' {
  declare module.exports: $Exports<'toxiclibsjs/util'>;
}
declare module 'toxiclibsjs/util/datatypes.js' {
  declare module.exports: $Exports<'toxiclibsjs/util/datatypes'>;
}
declare module 'toxiclibsjs/util/datatypes/ArraySet.js' {
  declare module.exports: $Exports<'toxiclibsjs/util/datatypes/ArraySet'>;
}
declare module 'toxiclibsjs/util/datatypes/FloatRange.js' {
  declare module.exports: $Exports<'toxiclibsjs/util/datatypes/FloatRange'>;
}
declare module 'toxiclibsjs/util/datatypes/UndirectedGraph.js' {
  declare module.exports: $Exports<'toxiclibsjs/util/datatypes/UndirectedGraph'>;
}
