// flow-typed signature: 53305b05766422d69ebbb709dc195d9b
// flow-typed version: <<STUB>>/what-input_v^5.1.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'what-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'what-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'what-input/dist/what-input' {
  declare module.exports: any;
}

declare module 'what-input/dist/what-input.min' {
  declare module.exports: any;
}

declare module 'what-input/Gulpfile' {
  declare module.exports: any;
}

declare module 'what-input/src/scripts/what-input' {
  declare module.exports: any;
}

// Filename aliases
declare module 'what-input/dist/what-input.js' {
  declare module.exports: $Exports<'what-input/dist/what-input'>;
}
declare module 'what-input/dist/what-input.min.js' {
  declare module.exports: $Exports<'what-input/dist/what-input.min'>;
}
declare module 'what-input/Gulpfile.js' {
  declare module.exports: $Exports<'what-input/Gulpfile'>;
}
declare module 'what-input/src/scripts/what-input.js' {
  declare module.exports: $Exports<'what-input/src/scripts/what-input'>;
}
