// flow-typed signature: bc088fdbdd1544ae5df685bd86d2e309
// flow-typed version: <<STUB>>/x3dom_v^1.7.2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'x3dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'x3dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'x3dom/x3dom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'x3dom/x3dom.js' {
  declare module.exports: $Exports<'x3dom/x3dom'>;
}
